odoo:
  image: odoo:16.0
  replicas: 1
  port: 8069
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"

postgres:
  image: postgres:13
  database: odoo
  username: odoo
  password: odoo123
  port: 5432
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"

service:
  type: NodePort
  port: 8069

ingress:
  enabled: false