odoo:
  image: odoo:16.0
  replicas: 3
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1000m"

postgres:
  image: postgres:13
  database: odoo_prod
  username: odoo_prod
  password: prod789secure
  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "1Gi"
      cpu: "400m"

service:
  type: NodePort